### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by rkenzhebekov** [aub/rails-backbone-forms#4]
Hello,

Thanks you for building a gem for backbone-forms gems. We've been using it since we started using backbone.js.

I think the latest gem is already outdated. Do you have a plan to build a new version which includes backbone-forms 0.14.1 version?

Best regards,
Ruslan.

**Comment by aub** [comment]
I'm not using this any more, so I've not been maintaining it. If you guys
want to send a pull request, I'd be happy to push up a new version of the
gem with it, and I could also transfer ownership to you if you want.

On Mon, Mar 3, 2014 at 9:36 PM, Ruslan Kenzhebekov <notifications@github.com

**Comment by rkenzhebekov** [comment]
@aub, opened a PR for 0.14.0 version.

**Comment by aub** [comment]
Pushed, thanks!

On Wed, Mar 5, 2014 at 1:40 AM, Ruslan Kenzhebekov <notifications@github.com
